version: '3.8'
volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/waboutzo/data/wordpress
  dbdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/waboutzo/data/dbdata
networks:
  app-network:
    driver: bridge
services:
  mariadb:
    container_name: mariadb
    env_file: .env
    build: 
      context: ./requirements/mariadb/
      args:
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD : ${MYSQL_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    restart: always
    volumes: 
      - dbdata:/var/lib/mysql
    networks:
      - app-network
  wordpress:
    depends_on: 
      - mariadb
    build: ./requirements/wordpress/
    container_name: wordpress
    restart: always
    env_file: .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - app-network
  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx/
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - app-network
